### ISSUE TITLE
No support for Github enterprise? Plugin hardcoded to github.com?

### ISSUE THREAD

**Issue by fnaum** [monterail/ghcr#52]
Hi,

I was trying to get this up and running in our GitHub Enterprise instance, but I think that this only work for github.com?

I've not much idea about ruby nor about chorme plugins, but I've changed in the ghcr API backend the files (app/controllers/commits_controller.rb and app/models/notification.rb) where I saw github.com harcoded with the url of our instance of Github.... but looks like this plugin might be harcoded to point to github.com

when I press Authorize on the chrome plugin I get:

https://github.com/login/oauth... user:email

I'd have expected https://myURL/login/oauth/authorize?....

Hopefully I'm doing something wrong, not 100% sure if this is an issue or a misconfiguration

Cheers
Fede

**Comment by hodak** [comment]
@fnaum You're right, we haven't prepared it to work with GitHub Enterpise. We're sad to say that we no longer support the project and can't address this issue. Sorry and wish you the best.

**Comment by fnaum** [comment]
no worries.
Thanks anyways
F
