### ISSUE TITLE
Extension is not available in Chrome Web Store 

### ISSUE THREAD

**Issue by koszcz** [monterail/ghcr#53]
Hi Guys, extension from link is not available in Chrome Web Store, did you remove it?

**Comment by teamon** [comment]
@chytreg ?

**Comment by chytreg** [comment]
@teamon No I did not remove it, but something wrong is with our google account.
Sorry for that. Unfortunately we don't maintain this project any more. As a code review tool for GitHub we advise to use https://reviewable.io
